apiVersion: v1
kind: ResourceQuota
metadata:
  name: frontend-quota
  namespace: frontend
spec:
  hard:
    requests.cpu: "1.5"
    requests.memory: "3Gi"
    limits.cpu: "3"
    limits.memory: "6Gi"
    pods: "10"
    services: "4"
    configmaps: "3"
    secrets: "2"
    persistentvolumeclaims: "2"