apiVersion: v1
kind: ResourceQuota
metadata:
  name: vault-quota
  namespace: vault
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "6Gi"
    limits.cpu: "6"
    limits.memory: "12Gi"
    pods: "6"
    services: "3"
    configmaps: "5"
    secrets: "5"
    persistentvolumeclaims: "6"

