apiVersion: v1
kind: LimitRange
metadata:
  name: database-limits
  namespace: database
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    default:
      cpu: "500m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "256Mi"
    max:
      cpu: "2"
      memory: "4Gi"