apiVersion: v1
kind: LimitRange
metadata:
  name: database-limits
  namespace: database
spec:
  limits:
  - type: Container
    default:
      cpu: "250m"
      memory: "512Mi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    max:
      cpu: "1"
      memory: "2Gi"