apiVersion: v1
kind: LimitRange
metadata:
  name: frontend-limits
  namespace: frontend
spec:
  limits:
  - type: Container
    default:
      cpu: "100m"
      memory: "256Mi"
    defaultRequest:
      cpu: "50m"
      memory: "128Mi"
    max:
      cpu: "500m"
      memory: "1Gi"