apiVersion: v1
kind: LimitRange
metadata:
  name: vault-limits
  namespace: vault
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    default:
      cpu: "1"
      memory: "2Gi"
    min:
      cpu: "250m"
      memory: "512Mi"
    max:
      cpu: "2"
      memory: "4Gi"