apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: vault
  annotations:
    kube-score/ignore: networkpolicy-targets-pod
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
