{{- if .Values.limitRange.enabled -}}
{{- $ns := .Release.Namespace -}}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "baseline.fullname" . }}-limits
  namespace: {{ $ns | quote }}
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
  {{- if and .Values.resourcePolicy.enabled .Values.resourcePolicy.keep.limitRange }}
  annotations:
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  limits:
    {{- toYaml .Values.limitRange.limits | nindent 4 }}
{{- end }}
