{{- if .Values.networkPolicy.defaultDeny.enabled -}}
{{- $ns := .Release.Namespace -}}
{{- $ann := dict -}}
{{- with .Values.networkPolicy.defaultDeny.annotations -}}
{{- $ann = merge $ann . -}}
{{- end -}}
{{- if and .Values.resourcePolicy.enabled .Values.resourcePolicy.keep.networkPolicy -}}
{{- $_ := set $ann "helm.sh/resource-policy" "keep" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "baseline.fullname" . }}-default-deny
  namespace: {{ $ns | quote }}
  labels:
    {{- include "baseline.labels" . | nindent 4 }}
  {{- if $ann }}
  annotations:
    {{- toYaml $ann | nindent 4 }}
  {{- end }}
spec:
  podSelector: {}
  policyTypes:
    {{- toYaml .Values.networkPolicy.defaultDeny.policyTypes | nindent 4 }}
{{- end }}
